############################################ testinst configuration  ############################################################################
services:
    #loads all the tm providers specified in the tmproviders section below. Creates all the necessary streams
    - org.yamcs.tctm.DataLinkInitialiser
    - class: org.yamcs.archive.XtceTmRecorder
    - org.yamcs.archive.FSEventDecoder
    - org.yamcs.archive.PpRecorder
    - org.yamcs.archive.AlarmRecorder
    - org.yamcs.archive.EventRecorder
    - org.yamcs.archive.ReplayServer
    - org.yamcs.archive.IndexServer
    - org.yamcs.parameter.SystemParametersCollector
    # create a realtime channel
    - class: org.yamcs.YProcessorCreatorService
      args: 
         name: "realtime"
         type: "realtime"

    #this one sets up the recording of the command history 
    - org.yamcs.cmdhistory.CommandHistoryRecorder
    - class: org.yamcs.hornetq.HornetQTmService
      args: [tm_realtime, tm_dump]

    - org.yamcs.web.YamcsWebService
    - org.yamcs.AlarmReporter
    - class: org.yamcs.parameterarchive.ParameterArchive
      args:
         realtimeFiller: 
             enabled: true
             flushInterval: 60
         backFiller:
             #warmupTime: 60 seconds default warmupTime
             enabled: true
             schedule: [{startSegment: 10, numSegments: 3}]
    - org.yamcs.hornetq.HornetQReplayServer

#name of the class that is used for the TM index. If not specified, org.yamcs.archive.GenericCccsdsTmIndex is used
#tmIndexer: 

#name of the class that is used to to generate events from the streams
eventDecoders: []

#config the tm providers started by the TmProviderAdapter
tmDataLinks:
    - class: com.odysseysr.proteus.yamcs.tctm.CfsUdpTmProvider
      name: tm_realtime
      spec: local
      stream: tm_realtime

#ppDataLinks:
    #- class: org.yamcs.simulation.SimulationPpProvider
    #  stream: pp_realtime
    #  args: {simulationDataPath: "etc/gs-simulation.xml"}


# config the tc uplinkers
tcDataLinks: 
    - class: com.odysseysr.proteus.yamcs.tctm.CfsUdpTcUplinker
      spec: local
      stream: tc_realtime

#Specify which MDB configuration to use, references a named section in mdb.yaml 
mdb: ocpoc

#Configuration for streams created at server startup
streamConfig:
  tm: 
    - name: "tm_realtime"
    - name: "tm_dump"
  cmdHist: ["cmdhist_realtime",  "cmdhist_dump"]
  event: ["events_realtime", "events_dump"]
  param: ["pp_realtime", "sys_param"]
  alarm: ["alarms_realtime"]
  tc: ["tc_realtime"]
