softsim:
    # Configuration of the active loaders
    # Valid loaders are: sheet, xtce or fully qualified name of the class
    - type: "sheet"
      spec: "/mdb/cfs-ccsds.xls"
      subLoaders:
           - type: "sheet"
             spec: "/mdb/PX4.xls"
           - type: "sheet"
             spec: "/mdb/CFE_ES.xls"
           - type: "sheet"
             spec: "/mdb/CFE_EVS.xls"
           - type: "sheet"
             spec: "/mdb/CFE_SB.xls"
           - type: "sheet"
             spec: "/mdb/CFE_TBL.xls"
           - type: "sheet"
             spec: "/mdb/CFE_TIME.xls"
           - type: "sheet"
             spec: "/mdb/CF.xls"
           - type: "sheet"
             spec: "/mdb/CI.xls"
           - type: "sheet"
             spec: "/mdb/CS.xls"
           - type: "sheet"
             spec: "/mdb/DS.xls"
           - type: "sheet"
             spec: "/mdb/FM.xls"
           - type: "sheet"
             spec: "/mdb/HK.xls"
           - type: "sheet"
             spec: "/mdb/HS.xls"
           - type: "sheet"
             spec: "/mdb/LC.xls"
           - type: "sheet"
             spec: "/mdb/MD.xls"
           - type: "sheet"
             spec: "/mdb/MM.xls"
           - type: "sheet"
             spec: "/mdb/SCH.xls"
           - type: "sheet"
             spec: "/mdb/SC.xls"
           - type: "sheet"
             spec: "/mdb/TO.xls"
           - type: "sheet"
             spec: "/mdb/MPU9250.xls"
           - type: "sheet"
             spec: "/mdb/MS5611.xls"
           - type: "sheet"
             spec: "/mdb/VC.xls"
           - type: "sheet"
             spec: "/mdb/RGBLED.xls"
           - type: "sheet"
             spec: "/mdb/EA.xls"
           - type: "sheet"
             spec: "/mdb/ULR.xls"
           - type: "sheet"
             spec: "/mdb/AMC.xls"
           - type: "sheet"
             spec: "/mdb/BAT.xls"
           - type: "sheet"
             spec: "/mdb/NAV.xls"

mavlink:
    # Configuration of the active loaders
    # Valid loaders are: sheet, xtce or fully qualified name of the class
    - type: "sheet"
      spec: "/mdb/Mavlink.xls"
      subLoaders:
           - type: "sheet"
             spec: "/mdb/common/Mavlink.xls"
